#!/bin/bash
shopt -s globstar nullglob nocaseglob
for file in **/*.gif; do
    if [[ -f "$file" ]]; then
        file_name=$(echo "$file" | sed 's/\.gif$//')
        echo "$file_name"
    fi
done | sort

echo
